# Perceptron

Exercício simples para treinar um perceptron

## Base
Rede do tipo Perceptron formada por um neurônio com três terminais de entrada, utilizando pesos iniciais w0 = 0.3, w1 = -0.5 e w2 = 0.4, limiar θ = 0.6 e uma taxa de aprendizado = 0.3.

In [1]:
# Dados iniciais
import numpy as np 
# Base de dados
# Classe -1  
A = np.array( [0, 0, 1] ) 
# Classe 1 
B = np.array( [1, 1, 0] ) 
# Pesos iniciais 
Pesos = np.array( [0.3, -0.5, 0.4] ) 
# Taxa de aprendizagem 
eta = 0.6 
# Viés 
bias = 0.3  

In [2]:
# Função para a soma ponderada 
# u = x0*w0 +  x1*w1 + x2*w2 -1*θ 
# m = x0*w0 +  x1*w1 + x2*w2
# u = m -1*θ
def somaPonderada(X,W):
  bias = 0.3
  m = np.multiply(X,W)
  u = np.sum(m) -1*bias
  return u 

In [3]:
# Função Degrau 
def funcaoAtivacao(u):
  if u >= 0:
    return 1
  else:
    return -1

In [4]:
# Função de saída 
def saida(X,W):
  u = somaPonderada(X,W)
  return funcaoAtivacao(u) 

In [5]:
# Função para ajustes dos pesos
# Parte cententral do processo de aprendizagem 
# novo wi  →  wi = wi +  η xi (d - y ) 
def ajustaPesos(eta,W,X,bias,d,y):
  e = d - y 
  novoW = W + eta*X*e
  novoB = bias + eta*(-1)*e 
  return novoW, novoB  

# Treinamento 
* Realizado manualmente para ilustrar o processo 
* Aprsenta uma entrada e calcula a saída de maneira iterativa 

## Iteração 1

In [6]:
# Entrada 001 saída -1 
d = -1 
y = saida(A,Pesos) 
print(y)
# Ajuste dos pesos 
Pesos,bias = ajustaPesos(eta,Pesos,A,bias,d,y) 
print(Pesos)
print(bias)  

# Entrada 110 saída +1
d = 1 
y = saida(B,Pesos) 
print(y)
# Ajuste dos pesos 
Pesos,bias = ajustaPesos(eta,Pesos,B,bias,d,y) 
print(Pesos)
print(bias) 

1
[ 0.3 -0.5 -0.8]
1.5
-1
[ 1.5  0.7 -0.8]
0.30000000000000004


## Iteração 2

In [7]:
# Entrada 001 saída -1 
d = -1 
y = saida(A,Pesos) 
print(y)
# Ajuste dos pesos 
Pesos,bias = ajustaPesos(eta,Pesos,A,bias,d,y) 
print(Pesos)
print(bias)  

# Entrada 110 saída +1
d = 1 
y = saida(B,Pesos) 
print(y)
# Ajuste dos pesos 
Pesos,bias = ajustaPesos(eta,Pesos,B,bias,d,y) 
print(Pesos)
print(bias) 

-1
[ 1.5  0.7 -0.8]
0.30000000000000004
1
[ 1.5  0.7 -0.8]
0.30000000000000004


## Testes

* As classes que pertencem aos padrões 110, 000, 100 e 011 

#Teste para padrão 110

In [8]:
# Padrão 110
T = np.array([1, 1, 0]) 
print("Saida para ",T," é ", saida(T,Pesos))

Saida para  [1 1 0]  é  1


#Teste para padrão 000

In [9]:
# Padrão 000
T = np.array([0, 0, 0]) 
print("Saida para ",T," é ", saida(T,Pesos))

Saida para  [0 0 0]  é  -1


#Teste para padrão 100

In [10]:
# Padrão 100
T = np.array([1, 0, 0]) 
print("Saida para ",T," é ", saida(T,Pesos))

Saida para  [1 0 0]  é  1


#Teste para padrão 011

In [11]:
# Padrão 011
T = np.array([0, 1, 1]) 
print("Saida para ",T," é ", saida(T,Pesos))

Saida para  [0 1 1]  é  -1
